# Generated by Django 3.2.9 on 2021-11-26 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('Video', 'Video'), ('test', 'Test')], max_length=15)),
                ('video_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Video Süresi Dakika: ')),
                ('video_sec', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Video Süresi Saniye: ')),
                ('cevap_a', models.CharField(default='Lorem İpsum A', max_length=150, verbose_name='Şık A')),
                ('cevap_b', models.CharField(default='Lorem İpsum B', max_length=150, verbose_name='Şık B')),
                ('cevap_c', models.CharField(default='Lorem İpsum C', max_length=150, verbose_name='Şık C')),
                ('cevap_d', models.CharField(default='Lorem İpsum D', max_length=150, verbose_name='Şık D')),
                ('cevap_e', models.CharField(default='Lorem İpsum E', max_length=150, verbose_name='Şık E')),
            ],
        ),
    ]
