# Generated by Django 3.2.9 on 2021-11-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencvdjango', '0003_userentry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentry',
            old_name='video_src',
            new_name='doc',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='image',
        ),
    ]
