# Generated by Django 3.2.5 on 2022-04-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencvdjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='cevaplar',
        ),
        migrations.AlterField(
            model_name='userentry',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='header',
            field=models.CharField(max_length=600),
        ),
        migrations.DeleteModel(
            name='Cevap',
        ),
    ]
