# Generated by Django 3.2.5 on 2022-04-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencvdjango', '0002_auto_20220405_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='rating',
        ),
    ]
